apiVersion: v1
kind: Service
metadata:
  name: resume-builder-service
spec:
  type: NodePort
  selector:
    app: resume-builder
  ports:
  - protocol: TCP
    port: 3000        # Service port
    targetPort: 3000  # Container port
    nodePort: 30080   # External access port (30000-32767 range)